name: Branch Build and Autoformat

run-name: Push to ${{ github.action_repository }} by @${{ github.actor }}

on:
  push:
    branches-ignore: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libcheck-dev \
          valgrind \
          clang-format \
          cppcheck \
          lcov \
          genhtml


    - name: configure
      run: ./configure

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck